version: "3"

services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Открываем только HTTP порт
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Монтируем конфиг nginx
    depends_on:
      - web
